# Generated by Django 4.2.1 on 2023-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmoney_info',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='addmoney_info',
            name='Category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Groceries', 'Groceries'), (
                'TV', 'TV'), ('Bolt', 'Bolt'), ('Debt', 'Debt'), ('Other', 'Other')], default='Rent', max_length=20),
        ),
    ]
