# Generated by Django 4.2.1 on 2023-05-27 00:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetpad', '0002_rename_quantity_addmoney_info_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMoney_info',
            new_name='AddExpense_info',
        ),
        migrations.RenameField(
            model_name='addexpense_info',
            old_name='add_money',
            new_name='add_expense',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Savings',
        ),
    ]
