# Generated by Django 4.2.1 on 2023-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0003_rename_addmoney_info_addexpense_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AlterField(
            model_name='addexpense_info',
            name='Category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Groceries', 'Groceries'), ('TV', 'TV'), ('Bolt', 'Bolt'), ('Other', 'Other')], default='Rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student'), ('Business', 'Business')], max_length=10),
        ),
    ]
