# Generated by Django 4.2.1 on 2023-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0004_remove_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense_info',
            name='Category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Groceries', 'Groceries'), ('TV', 'TV'), ('Data', 'Data'), ('Bolt', 'Bolt'), ('Other', 'Other')], default='Rent', max_length=20),
        ),
    ]
